rewrite_vids = true
# root_dir
# overwrite_lead_lag_edge_data = true
# overwrite_plots = true
# norm_videos_dir
# runs_to_quantify
# video_suffixes
# time_of_interest_sec
# num_secs_to_process
# bw_threshold_default
# px_per_mm
# magnet_distance_mm
# frames_per_real_sec
# default_frames_per_real_sec
